services:
  - type: web
    name: ideal-ai-college-assistant
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --graceful-timeout 30
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: NEWS_DATA_API
        sync: false
      - key: GNEWS_API
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPEN_ROUTER_API
        sync: false
