services:
  - type: web
    name: ideal-ai-college-assistant
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPEN_ROUTER_API
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: NEWS_DATA_API
        sync: false
      - key: GNEWS_API
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
        value: "change-this-in-production-please"